### ISSUE TITLE
Pesquisar potenciais modelos

### ISSUE THREAD

**Issue by Jonathan-Oliveira** [deeplearningunb/EconomIA#9]
## Descrição

Assim como qualquer solução de software um modelo de regressão pode ser feito de diversas formas, para escolher o melhor modelo de regressão que possa se encaixar no nosso projeto temos que realizar uma pesquisa para analisar se os modelos com transferência de aprendizagem serão vantajosos ou teremos que construir nosso modelo camada por camada

## Objetivo

Elicitar os melhores modelos para regressão.

## Tarefas

- [x] Pesquisar modelos

## Critérios de Aceitação

- [x] Documento com os prós e contras de cada modelo

**Comment by julisous** [comment]
[Pesquisa_modelo_de_regressao.pdf](https://github.com/deeplearningunb/EconomIA/files/8636482/Pesquisa_modelo_de_regressao.pdf)

**Comment by julisous** [comment]
[Pesquisa_modelo_de_regressao.pdf](https://github.com/deeplearningunb/EconomIA/files/8636483/Pesquisa_modelo_de_regressao.pdf)
